/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "A_aliases.h"
#include "A.h"
#include "B_aliases.h"
#include "B.h"
#include "C_aliases.h"
#include "C.h"
#include "D_aliases.h"
#include "D.h"
#include "E_aliases.h"
#include "E.h"
#include "F_aliases.h"
#include "F.h"
#include "G_aliases.h"
#include "G.h"
#include "Clock_1.h"
#include "BOT1_aliases.h"
#include "BOT1.h"
#include "SWITCHE_aliases.h"
#include "SWITCHE.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "LED4_aliases.h"
#include "LED4.h"
#include "LED5_aliases.h"
#include "LED5.h"
#include "LED6_aliases.h"
#include "LED6.h"
#include "LED7_aliases.h"
#include "LED7.h"
#include "LED8_aliases.h"
#include "LED8.h"
#include "RGB_aliases.h"
#include "RGB.h"
#include "BOTON2_aliases.h"
#include "BOTON2.h"
#include "BUZZER_aliases.h"
#include "BUZZER.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

