/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "A_aliases.h"
#include "A.h"
#include "B_aliases.h"
#include "B.h"
#include "C_aliases.h"
#include "C.h"
#include "D_aliases.h"
#include "D.h"
#include "E_aliases.h"
#include "E.h"
#include "F_aliases.h"
#include "F.h"
#include "G_aliases.h"
#include "G.h"
#include "Led_0_aliases.h"
#include "Led_0.h"
#include "Led_1_aliases.h"
#include "Led_1.h"
#include "Led_2_aliases.h"
#include "Led_2.h"
#include "Led_3_aliases.h"
#include "Led_3.h"
#include "Led_4_aliases.h"
#include "Led_4.h"
#include "Led_5_aliases.h"
#include "Led_5.h"
#include "Led_6_aliases.h"
#include "Led_6.h"
#include "Led_7_aliases.h"
#include "Led_7.h"
#include "Boton2_aliases.h"
#include "Boton2.h"
#include "Clock_2.h"
#include "X_aliases.h"
#include "X.h"
#include "boton1_aliases.h"
#include "boton1.h"
#include "RGB_aliases.h"
#include "RGB.h"
#include "Buzzer_aliases.h"
#include "Buzzer.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

