/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Button_aliases.h"
#include "Button.h"
#include "Clock_1.h"
#include "Interrupt.h"
#include "SW_vel_aliases.h"
#include "SW_vel.h"
#include "Seg_aliases.h"
#include "Seg.h"
#include "Com_aliases.h"
#include "Com.h"
#include "Segments.h"
#include "Contador.h"
#include "Timer.h"
#include "SW_aliases.h"
#include "SW.h"
#include "LEDS_aliases.h"
#include "LEDS.h"
#include "SW_buzz_aliases.h"
#include "SW_buzz.h"
#include "Clock_2.h"
#include "Buzzer_aliases.h"
#include "Buzzer.h"
#include "DosP_aliases.h"
#include "DosP.h"
#include "Segments_ClkInternal.h"
#include "Segments_Seg_Driver_L.h"
#include "Segments_Com_Driver.h"
#include "Segments_DMA_Com_dma.h"
#include "Segments_DMA_Seg_dma.h"
#include "Segments_DMA_BC_dma.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

